### PR TITLE
Update the decrypt call to use the v2+ signature

### PR DESCRIPTION
**Pull request by mjneth**
Change is required to work with v2+ of the python google API changes for use in drbot

### CODE REVIEW

**Review by maroux — APPROVED** [review]

**Review by maroux — CHANGES_REQUESTED** [review]
wait other requirements.txt files need to be re-compiled as well.

**Comment by mjneth** [comment]
> wait other requirements.txt files need to be re-compiled as well.

Do you have a set of commands you run for the necessary steps you could share? That might be quicker so we can document what your dev and release flow is for this repo.

**Comment by maroux** [comment]
> > wait other requirements.txt files need to be re-compiled as well.
> 
> Do you have a set of commands you run for the necessary steps you could share? That might be quicker so we can document what your dev and release flow is for this repo.


`make pip_compile` didn't work?

**Comment by mjneth** [comment]
> > > wait other requirements.txt files need to be re-compiled as well.
> > 
> > 
> > Do you have a set of commands you run for the necessary steps you could share? That might be quicker so we can document what your dev and release flow is for this repo.
> 
> `make pip_compile` didn't work?

Ah hadn't checked the make file. It's not working at the moment but i'm trying to work through the issues. Seems like maybe it's related to conflicting package versions or newer package versions not working since it looks like this code base hasn't been touched in 4 years.

So far:
- Had to pin setuptools==58 to fix `error in ipdb setup command: use_2to3 is invalid.`
- Getting `ERROR: No matching distribution found for setuptools>=40.8.0` though adding `--no-build-isolation` to the pip-compile command to resolve that but then it started erroring on other packages `ERROR: Could not find a version that satisfies the requirement google-cloud-kms>=2`. It seems to be the `--no-index` option causing it.

Will continue to work through these to figure out what's wrong and get the readme updated with any necessary changes.

**Comment by mjneth** [comment]
> > > > wait other requirements.txt files need to be re-compiled as well.
> > > 
> > > 
> > > Do you have a set of commands you run for the necessary steps you could share? That might be quicker so we can document what your dev and release flow is for this repo.
> > 
> > 
> > `make pip_compile` didn't work?
> 
> Ah hadn't checked the make file. It's not working at the moment but i'm trying to work through the issues. Seems like maybe it's related to conflicting package versions or newer package versions not working since it looks like this code base hasn't been touched in 4 years.
> 
> So far:
> 
> * Had to pin setuptools==58 to fix `error in ipdb setup command: use_2to3 is invalid.`
> * Getting `ERROR: No matching distribution found for setuptools>=40.8.0` though adding `--no-build-isolation` to the pip-compile command to resolve that but then it started erroring on other packages `ERROR: Could not find a version that satisfies the requirement google-cloud-kms>=2`. It seems to be the `--no-index` option causing it.
> 
> Will continue to work through these to figure out what's wrong and get the readme updated with any necessary changes.

I thought it might be related to pip>20 so I went back to pip==19 but got a new error (https://github.com/jazzband/pip-tools/issues/714) but going all the way back to pip==18 and pip-tools==3.2.0 made it work.

Was this codebase a temporary measure like the forked terraform provider? Do other options exist now so we don't need to maintain this anymore?

**Review by maroux — APPROVED** [review]

**Pull request merged**
